apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dep-kube-leo
  labels:
    app: test-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-kube
  template:
    metadata:
      labels:
        app: test-kube
        version: v17
    spec:
      containers:
      - name: test-kube
        image: docker.sds-act.com/test-dep-kube:17
        ports:
        - containerPort: 9000
      imagePullSecrets:
      - name: act-docker-registry-key